name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run: |
        docker login --username yelloweq --password ${{ secrets.PERSONAL_ACCESS_TOKEN }} ghcr.io
        docker build --platform linux/arm64 --target frankenphp_prod -t ghcr.io/yelloweq/portfolio:prod --no-cache .
        docker push ghcr.io/yelloweq/portfolio:prod
